apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-prometheus-rule
  namespace: monitoring
spec:
  groups:
    - name: example-rules
      rules:
        - alert: HighCPUUsage
          expr: node_cpu_seconds_total{mode="user"} > 80
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "CPU usage is too high"
